services:
  portfolio:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vb-portfolio
    restart: unless-stopped
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portfolio.rule=Host(`nhr-ai.com`)"
      - "traefik.http.routers.portfolio.entrypoints=websecure"
      - "traefik.http.routers.portfolio.tls.certresolver=letsencrypt"
